Updated Autumn-to-Julia Compiler (on + object) and Sketch Compiler
zenna/CausalDiscovery.jl pull request #40
Opened 2020-10-03 12:54 UTC by riadas

Remaining To-Do:
1. Refactor code/add documentation to make it more understandable
2. Fix minor issues in Sketch compiler
3. Add tests

2020-10-06 04:13 UTC, zenna requested changes
Nice work.  Mostly superficial comments.  Will need to talk to you to figure out any structural changes.

2020-10-06 04:13 UTC, zenna commented on src/Autumn/compile.jl
>    if (aexpr.head == :program)
Unnecessary parens

2020-10-06 04:13 UTC, zenna commented on src/Autumn/compile.jl
>      lines = filter(x -> x !== :(), map(arg -> compile(arg, historydata, aexpr), aexpr.args))
You're filtering `lines` twice for `:()` twice, also in one case you're using `!=` and in another `!==`, which should it be?

2020-10-06 04:13 UTC, zenna commented on src/Autumn/compile.jl
> +    stateStruct = compilestate_sk(metadata)
camelCase is for types!

2020-10-06 04:13 UTC, zenna commented on src/Autumn/myfile.txt
> +int ARR_BND = 10;
What is this file? It probably shouldn't be called myfile.text

2020-10-06 04:13 UTC, zenna commented on src/Autumn/sketch/autumnParticles.sk
> +include "autumnStandardLibrary.sk";
Should this file be in the repo? Why so many commented lines?

2020-10-06 04:13 UTC, zenna commented on src/Autumn/sketch/helloworld.sk
> +struct Particle extends Object {
Should this file be in the repo?

2020-10-06 04:13 UTC, zenna commented on src/Autumn/sketch/temp.sk
> +include "autumnStandardLibrary.sk";
Should this file....

2020-10-06 04:13 UTC, zenna commented on src/Autumn/sketch/temp2.sk
> +include "autumnStandardLibrary.sk";
Should ....

2020-10-06 04:13 UTC, zenna commented on src/Autumn/sketchcompileroutput.txt
> +int ARR_BND = 10;
Shou.....

2020-10-06 04:13 UTC, zenna commented on test/Autumn/eval.jl
> +mod = eval(compiletojulia(aexpr))
Use varname other than `mod`, using `mod` prevents you from running this in the repl since mod is exported from Base.

2020-10-06 04:13 UTC, zenna commented on test/Autumn/eval.jl
> +
Put this in a testset

2020-10-06 04:13 UTC, zenna commented on src/Autumn/autumnstdlib.jl
> +module AutumnStandardLibrary
rename as `AutumnSketchStdLib` or something

2020-10-06 04:13 UTC, zenna commented on src/Autumn/compileutils.jl
>    uniformChoiceFunction = builtInDict["uniformChoice"]
Move these builtins to another file / module

2020-10-06 04:13 UTC, zenna commented on src/Autumn/compileutils.jl
>      :($(Symbol(string(expr.args[2]) * "Prev"))($(map(compile, expr.args[3:end])...)))
This little function might make your life less verbose (typed `*\_s`):

```
julia> a::Symbol *ₛ b::Symbol = Symbol(string(a) * string(b))
*ₛ (generic function with 1 method)

julia> :hello *ₛ :world
:helloworld
```

2020-10-06 04:13 UTC, zenna commented on src/Autumn/compileutils.jl
> +  # println("here: ")
rm comments

2020-10-06 04:13 UTC, zenna commented on src/Autumn/compile.jl
> +  historydata = Dict([("external" => [au"""(external (: click Click))""".args[1], au"""(external (: left KeyPress))""".args[1], au"""(external (: right KeyPress))""".args[1], au"""(external (: up Key
I'm a bit confused about this object 

1. You should probably use symbols instead of strings
2. You don't need to create a vector, e.g. `Dict(1=>2, 3=>4)` is fine
3. It should probably be a struct, it seems to be quite hetrogenous

2020-10-06 04:13 UTC, zenna commented on src/Autumn/compileutils.jl
> +function compile(expr::AExpr, data::Dict{String, Any}, parent::Union{AExpr, Nothing}=nothing)::Expr
Use `aex` for `Aexpr`s, shorter and ore informative. reserve expr for Julia `Expr`s

2020-10-13 05:52 UTC, riadas commented on src/Autumn/sketch/autumnParticles.sk
> +include "autumnStandardLibrary.sk";
This is the working Sketch file for the particles example (the one that we were testing in August). The commented lines are from all the experimentation with removing/adding generator branches to test Sketch's performance on particles. This branch has all the Sketch compiler progress along with the finalized Julia compiler, so I believe this file should be in the repo.

2023-03-16 16:27 UTC, merged